#!/bin/bash
clear

NOTIFY () {
clear
clear
msg -bar
msg -ama "     [ VPS - AR - MOD \033[1;97m ❌ MOD By @Kalix1 ❌\033[1;33m ]"
msg -bar
msg -ama " Notify-BOT (Notificasion Remota)| VPS-AR-MOD By @Kalix1 "
msg -bar
echo -e "\033[1;94m Notify-BOT es un simple notificador de:"
echo -e "\033[1;94m >> Usuario Expirado"
echo -e "\033[1;94m >> Usuario Eliminado"
echo -e "\033[1;94m >> Avisos de VPS Reiniciada"
echo -e "\033[1;94m >> Avisos de Monitor de Protocolos"
echo -e "\033[1;97m Inicie BOT de Telegram @RealNetRS_bot"
echo -e "\033[1;92m ¡¡ Para sacar su ID entre al BOT @USA1_BOT"
echo -e "\033[1;92m Aparesera algo parecido 👤 → Tu ID es: 45145564"
msg -bar
echo -e "\033[1;93mIgrese un nombre para el VPS:\033[0;37m"; read -p " " nombr
echo "${nombr}" > /etc/VPS-MX/controlador/nombre.log
echo -e "\033[1;93mIgrese su ID 👤:\033[0;37m"; read -p " " idbot
echo "${idbot}" > /etc/VPS-MX/controlador/IDT.log 
msg -bar
echo -e "\033[1;32m              ID AGREGADO CON EXITO"
msg -bar
NOM="$(less /etc/VPS-MX/controlador/nombre.log)"
NOM1="$(echo $NOM)"
IDB1=`less /etc/VPS-MX/controlador/IDT.log` > /dev/null 2>&1
IDB2=`echo $IDB1` > /dev/null 2>&1

KEY="1210661669:AAF7lIPjGIlWsBIiXDzUyO7qyG1MmvIkY28"
URL="https://api.telegram.org/bot$KEY/sendMessage"
MSG="⚠️ ►► AVISO DE VPS: $NOM1 ⚠
👉 ►► MENSAJE DE PRUEBA
🔰 ►► NOTI-BOT ACTIVADO CORRECTAMENTE"
curl -s --max-time 10 -d "chat_id=$IDB2&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null

echo -e "\033[1;34m            SE ENVIO MENSAJE DE PRUEBA "
}
